apiVersion: v1
kind: Pod
metadata:
  name: webapp
  namespace: devproject
  labels: #to map it with the service
    app: web
    env: dev
spec:
  containers:
    - name: webcon
      image: scorpneedhi/springapp:v1
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
          name: apache
          protocol: TCP
      resources:
        requests:
          memory: "200Mi"
          cpu: "200m"
        limits:
          memory: "300Mi"
          cpu: "400m"
